---

version: '3.7'
services:
  ingest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8888:8888"
    command: python -m ingest.main
